basePath: /api/v1
definitions:
  dtos.SignInDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dtos.SignUpDTO:
    properties:
      birthday:
        type: string
      email:
        type: string
      fullName:
        type: string
      gender:
        enum:
        - Male
        - Female
        type: string
      password:
        minLength: 8
        type: string
      phone:
        type: string
    required:
    - email
    - fullName
    - password
    type: object
  handlers.HeathCheckResponse:
    properties:
      message:
        type: string
    type: object
  proto.SignInResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  proto.SignUpResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample Swagger API for a Go Gin application.
  termsOfService: https://example.com/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns a simple health check response indicating the status of
        the service.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HeathCheckResponse'
      summary: Health check endpoint
      tags:
      - Health check
  /sign-in:
    post:
      consumes:
      - application/json
      description: Handles the user sign-in process by validating input and authenticating
        the user via gRPC.
      parameters:
      - description: User sign-in data in JSON format
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dtos.SignInDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/proto.SignInResponse'
        "400":
          description: Bad Request
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            type: object
      summary: Handles user sign-in
      tags:
      - Authentication
  /sign-up:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to sign up and create a new account.
        It expects a JSON payload containing user information.
      operationId: signUp
      parameters:
      - description: User information for registration
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dtos.SignUpDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/proto.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: Register a new user account
      tags:
      - Authentication
swagger: "2.0"
